services:
  _defaults:
    autowire: true
    autoconfigure: true

  BestIt\LicenseCheck\:
    resource: '../../src/*'

  _instanceof:
    BestIt\LicenseCheck\LicenseLoader\LicenseLoaderInterface:
      tags: [ 'app.license_loader' ]

  Finder:
    class: Symfony\Component\Finder\Finder
    shared: false

  BestIt\LicenseCheck\LicenseLoader\ComposerLicenseLoader:
    arguments:
      - '@Finder'

  BestIt\LicenseCheck\LicenseLoader\NodeLicenseLoader:
    arguments:
      - '@Finder'

  BestIt\LicenseCheck\Checker:
    arguments:
      - !tagged_iterator app.license_loader

  BestIt\LicenseCheck\Application:
    public: true
    arguments:
      - '@BestIt\LicenseCheck\Command\LicenseCheckCommand'