language: php

sudo: false

php:
  - 8.0

install:
  - composer self-update
  - composer install --no-interaction --prefer-source

script:
  - ./vendor/bin/phpcs -n
  - ./vendor/bin/phpunit
  - ./vendor/bin/phpcpd src
  - ./vendor/bin/phpstan -l8 analyse ./src